name: Build macOS Sierra Compatible App

on: [push]

jobs:
  build:
    runs-on: macos-latest  # Uses the latest macOS runner (ARM by default)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set macOS Deployment Target
        run: echo "MACOSX_DEPLOYMENT_TARGET=10.12" >> $GITHUB_ENV

      - name: Install Python 3.8 (x86_64)
        run: |
          arch -x86_64 /opt/homebrew/bin/brew install python@3.8  # ✅ Use correct Homebrew path
          arch -x86_64 /opt/homebrew/bin/python3.8 -m venv venv  # ✅ Create x86_64 virtualenv

      - name: Set up Python Virtual Environment (x86_64)
        run: |
          source venv/bin/activate
          arch -x86_64 python3 -m pip install --upgrade pip
          arch -x86_64 pip install pandas  # ✅ Install x86_64 version of pandas
          arch -x86_64 pip install pyinstaller==6.12.0  # ✅ Install latest PyInstaller
          arch -x86_64 pip install PyQt6==6.2.3  # ✅ Last version that supports macOS Sierra
          arch -x86_64 pip install setuptools==58  # ✅ Avoid compatibility issues

      - name: Debug Repository Structure
        run: ls -R  # ✅ List files to verify `main.py` exists

      - name: Build macOS App (x86_64 only)
        run: |
          source venv/bin/activate
          pyinstaller --windowed --name="YourAppName" --target-arch=x86_64 --hidden-import=pandas main.py

      - name: Upload built app
        uses: actions/upload-artifact@v4
        with:
          name: macOS-App
          path: dist/
