name: Build macOS Sierra Compatible App

on: [push]

jobs:
  build:
    runs-on: macos-latest  # Uses the latest macOS runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set macOS Deployment Target
        run: echo "MACOSX_DEPLOYMENT_TARGET=10.12" >> $GITHUB_ENV

      - name: Set up Python Virtual Environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python3 -m pip install --upgrade pip
          pip install pyinstaller==4.5.1  # ✅ Keep PyInstaller version that worked
          pip install PyQt6==6.2.3  # ✅ Last version that supports macOS Sierra
          pip install setuptools==58  # ✅ Avoid compatibility issues
          pip install pandas numpy  # ✅ Ensure `pandas` and `numpy` are installed

      - name: Debug Repository Structure
        run: ls -R  # ✅ List files to verify `main.py` exists

      - name: Build macOS Sierra-Compatible App
        run: |
          source venv/bin/activate
          pyinstaller --windowed --name="YourAppName" --target-arch=x86_64 --hidden-import=pandas --hidden-import=numpy main.py

      - name: Upload built app
        uses: actions/upload-artifact@v4
        with:
          name: macOS-App
          path: dist/
