name: Build macOS Sierra Compatible App

on: [push]

jobs:
  build:
    runs-on: macos-latest  # Uses the latest macOS runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Set macOS Deployment Target
        run: echo "MACOSX_DEPLOYMENT_TARGET=10.12" >> $GITHUB_ENV

      - name: Set up Python Virtual Environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python3 -m pip install --upgrade pip
          pip install pyinstaller==4.5.1  # ✅ Keep PyInstaller at the version that worked
          pip install PyQt6==6.2.3  # ✅ Last version that supports macOS Sierra
          pip install setuptools==58  # ✅ Avoid compatibility issues
          pip install pandas numpy  # ✅ Ensure `pandas` and `numpy` are installed

      - name: Remove Existing Code Signatures (Fixes PyInstaller Signing Issue)
        run: |
          find venv -name "*.so" -exec codesign --remove-signature {} \; || true
          find venv -name "*.dylib" -exec codesign --remove-signature {} \; || true
          find venv -name "*.o" -exec codesign --remove-signature {} \; || true
          find venv -name "*.bundle" -exec codesign --remove-signature {} \; || true

      - name: Debug Repository Structure
        run: ls -R  # ✅ List files to verify `main.py` exists
        
      - name: Patch PyInstaller to Skip Code Signing Fix
        run: |
          sed -i '' 's/assert linkedit_seg.fileoff + linkedit_seg.filesize ==/# assert linkedit_seg.fileoff + linkedit_seg.filesize ==/' venv/lib/python3.8/site-packages/PyInstaller/utils/osx.py

      - name: Build macOS Sierra-Compatible App (Fix Code Signing)
        run: |
          source venv/bin/activate
          pyinstaller --windowed --name="YourAppName" --target-arch=x86_64 \
                      --hidden-import=pandas --hidden-import=numpy \
                      --osx-bundle-identifier=com.dummy.placeholder main.py

      - name: Upload built app
        uses: actions/upload-artifact@v4
        with:
          name: macOS-App
          path: dist/
