name: Build macOS Sierra Compatible App

on: [push]

jobs:
  build:
    runs-on: macos-latest  # Uses the latest macOS runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Set macOS Deployment Target
        run: echo "MACOSX_DEPLOYMENT_TARGET=10.12" >> $GITHUB_ENV

      - name: Delete and Recreate Virtual Environment
        run: |
          rm -rf venv  # ✅ Remove broken venv
          python3 -m venv venv
          source venv/bin/activate
          python3 -m pip install --upgrade pip
          pip install --force-reinstall pyinstaller==4.5.1  # ✅ Restore original PyInstaller
          pip install PyQt6==6.2.3 pandas numpy setuptools==58  # ✅ Ensure dependencies

      - name: Patch PyInstaller to Skip Code Signing Fix
        run: |
          sed -i '' 's/assert linkedit_seg.fileoff + linkedit_seg.filesize ==.*$/# Disabled code signing assertion/' \
            venv/lib/python3.8/site-packages/PyInstaller/utils/osx.py || true

      - name: Build macOS Sierra-Compatible App
        run: |
          source venv/bin/activate
          pyinstaller --windowed --name="YourAppName" --target-arch=x86_64 \
                      --hidden-import=pandas --hidden-import=numpy \
                      --osx-bundle-identifier=com.dummy.placeholder main.py

      - name: Upload built app
        uses: actions/upload-artifact@v4
        with:
          name: macOS-App
          path: dist/
